using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

namespace Lokanta.Game.Ui
{
    /// <summary>
    /// Hints shown ONCE. Not a tutorial, a reminder.
    ///
    /// docs/16 describes a minute-by-minute tutorial and there was not one
    /// line of it in the code. What a new player saw on day one: an empty
    /// hall, four grey buttons and a red number with no name. All four of
    /// the four sub-screens say "there is nothing for you to do here"
    /// (stock full, menu locked, hall crew empty, equipment all the same
    /// price). The only meaningful action is "Open service" and that is a
    /// door with NO WAY BACK.
    ///
    /// NOT a wall of text: one sentence, next to the button it is about,
    /// the first time it appears. It says only the three things the player
    /// has to know, without eating into their tap budget (docs/16: 40-60
    /// taps a day).
    ///
    /// Once seen it never appears again, and that is stored ON THE DEVICE,
    /// not in the save: making a player who starts a second campaign read
    /// the same sentences again pushes them away from the game itself.
    /// </summary>
    public static class Hints
    {
        /// <summary>A hint to show. Null if there is none.</summary>
        public sealed class Hint
        {
            public readonly string Id;
            public readonly string TextKey;

            /// <summary>
            /// The value the text substitutes for {0}. Null means none.
            ///
            /// The intervention hint once had "four a day" HARD-CODED into
            /// it, when the number comes from content/economy.json and that
            /// file is GENERATED by the balance tool. Change the balance and
            /// the hint would quietly start lying.
            /// </summary>
            public System.Func<Lokanta.Core.Sim.Simulation, object> Arg;

            public Hint(string id, string textKey,
                        System.Func<Lokanta.Core.Sim.Simulation, object> arg = null)
            { Id = id; TextKey = textKey; Arg = arg; }
        }

        // All three state a RULE; none of them describes a button.
        //
        //   1. Opening service is the only decision with no way back.
        //   2. With no dish on the menu a guest turns round at the door -
        //      a rule the game only taught by LOSING, and even the loss
        //      only showed up in the evening report, and only when it was
        //      greater than zero.
        //   3. The intervention allowance is per day and covers ALL THREE
        //      AT ONCE; the screen only said "Allowance 4", with no clue
        //      what it was an allowance of.
        //
        // THE IDS ARE PlayerPrefs KEYS ("lokanta.ipucu." + id), so they
        // stay exactly as they are: renaming one would make every player
        // who has already dismissed a hint see it again.
        private static readonly Hint Service = new Hint("servis", "ui.hint.service");
        private static readonly Hint Menu = new Hint("menu", "ui.hint.menu");
        private static readonly Hint Interventions = new Hint(
            "mudahale", "ui.hint.interventions", s => s.InterventionsToday);
            // InterventionsPerDay is the BASE number (4). The daily
            // allowance grows with the table count (InterventionsToday) -
            // because the hint read the base, it told the player they had
            // FEWER than they did as soon as they first expanded. The text
            // was right, the wiring was wrong.
        private static readonly Hint Rent = new Hint("kira", "ui.hint.rent");
        private static readonly Hint Price = new Hint("fiyat", "ui.hint.price");
        private static readonly Hint Staff = new Hint("personel", "ui.hint.staff");
        private static readonly Hint Select = new Hint("secim", "ui.hint.select");

        // THE REPUTATION CEILING. The game's most important progression
        // rule, and it was written down nowhere: reputation is capped by
        // the table count, and a player pressed up against the cap watches
        // the number refuse to move however well they run the service.
        // Measured: a player playing well hits 75 on 7 tables and sits
        // there for 32 days.
        private static readonly Hint Cap = new Hint(
            "tavan", "ui.hint.cap", s => s.ReputationCapCenti / 100);

        private const string Prefix = "lokanta.ipucu.";

        private static readonly HashSet<string> Shown = new HashSet<string>();

        /// <summary>True if this hint has been seen before.</summary>
        public static bool Seen(Hint h)
        {
            if (h == null) return true;
            if (Shown.Contains(h.Id)) return true;
            return PlayerPrefs.GetInt(Prefix + h.Id, 0) != 0;
        }

        public static void MarkSeen(Hint h)
        {
            if (h == null) return;
            Shown.Add(h.Id);
            PlayerPrefs.SetInt(Prefix + h.Id, 1);
            PlayerPrefs.Save();
        }

        /// <summary>Forgets every hint. Called from the settings screen.</summary>
        public static void Reset()
        {
            Shown.Clear();
            foreach (Hint h in All) PlayerPrefs.DeleteKey(Prefix + h.Id);
            PlayerPrefs.Save();
        }

        /// <summary>
        /// Counts every hint as SEEN.
        ///
        /// For store screenshots: the hint strip sits on top of the hall,
        /// so what shows up in a store listing is the tutorial rather than
        /// the game. NOT used on the measurement tour - there the opposite
        /// is wanted (Reset), because the onboarding layer has to be
        /// measured too.
        /// </summary>
        public static void MarkAllSeen()
        {
            foreach (Hint h in All) MarkSeen(h);
        }

        /// <summary>
        /// Every hint. Reset() walks this array, so a hint that is not
        /// added here does not come back even when the player asks to
        /// "show the hints again" - which is exactly how Cap came to be
        /// missing from it.
        /// </summary>
        private static readonly Hint[] All =
            { Service, Menu, Interventions, Rent, Price, Staff, Select, Cap };

        // =====================================================================
        /// <summary>
        /// The hint that should be shown right now. Null if there is none.
        ///
        /// The order is not IMPORTANCE, it is TIME: the player learns to
        /// open service first, then the menu, then intervention, and the
        /// rent last. Showing two at once gets neither of them read.
        /// </summary>
        public static Hint Current(Lokanta.Core.Sim.Simulation sim)
        {
            if (sim == null) return null;

            if (sim.Phase == Lokanta.Core.Sim.DayPhase.Morning)
            {
                if (!Seen(Service)) return Service;
                if (sim.Day >= 2 && !Seen(Menu)) return Menu;
                // Rent, on the day it falls due, comes before everything
                // else: with no money in the till that day the player goes
                // into debt, and they need to learn that first.
                if (sim.DaysToRent <= 1 && !Seen(Rent)) return Rent;
                if (sim.Day >= 3 && !Seen(Price)) return Price;
                if (sim.Day >= 4 && !Seen(Staff)) return Staff;
                // WHEN THEY ARE PRESSED AGAINST THE CEILING: the rule only
                // means anything at that moment.
                if (sim.ReputationCenti >= sim.ReputationCapCenti && !Seen(Cap))
                    return Cap;
                return null;
            }

            if (sim.Phase == Lokanta.Core.Sim.DayPhase.Service)
            {
                if (!Seen(Interventions)) return Interventions;
                // Picking a table comes on the SECOND service: the first
                // one already goes on learning what an intervention is.
                if (sim.Day >= 2 && !Seen(Select)) return Select;
            }

            return null;
        }

        // =====================================================================
        /// <summary>
        /// The hint strip. A one-sentence, dismissable box that sits over
        /// the top of the screen.
        ///
        /// NOT a permanent tutorial layer: once dismissed it never comes
        /// back, and it takes exactly one tap out of the player's tap
        /// budget (docs/16: 40-60 taps a day).
        /// </summary>
        public static VisualElement Strip(Hint h, Lokanta.Core.Sim.Simulation sim,
                                         System.Action onDismiss)
        {
            if (h == null) return null;

            VisualElement box = new VisualElement();
            box.style.flexDirection = Theme.RowFlow;
            box.style.alignItems = Align.Center;
            box.style.backgroundColor = new Color(0.20f, 0.17f, 0.11f);
            // THE SIDE THE STRIPE AND THE WIDE PADDING GO ON IS THE SIDE THE
            // WRITING STARTS ON.
            //
            // This is the only ONE-SIDED decoration in the interface. In
            // Arabic the text starts from the right; had the stripe stayed
            // on the left, the emphasis line would point at the end of the
            // sentence.
            bool rtl = Loc.IsRightToLeft;
            if (rtl)
            {
                box.style.borderRightWidth = 3;
                box.style.borderRightColor = Theme.Warn;
                box.style.paddingRight = Theme.Pad;
                box.style.paddingLeft = Theme.Gap;
            }
            else
            {
                box.style.borderLeftWidth = 3;
                box.style.borderLeftColor = Theme.Warn;
                box.style.paddingLeft = Theme.Pad;
                box.style.paddingRight = Theme.Gap;
            }
            box.style.paddingTop = Theme.Gap;
            box.style.paddingBottom = Theme.Gap;
            box.style.marginBottom = Theme.Gap;

            string body = h.Arg != null && sim != null
                ? Loc.T(h.TextKey, h.Arg(sim))
                : Loc.T(h.TextKey);
            Label text = Theme.Text(body, Theme.FontSmall, Theme.Ink);
            // It does not fit on one line: it has to wrap, or half the
            // sentence ends up off the screen. Measured at 873x393.
            text.style.whiteSpace = WhiteSpace.Normal;
            text.style.flexGrow = 1;
            text.style.flexShrink = 1;
            box.Add(text);

            Button ok = Theme.Btn(Loc.T("ui.hint.ok"), () =>
            {
                MarkSeen(h);
                if (onDismiss != null) onDismiss();
            });
            // The touch target is THE THEME's own measure (52 dp). It used
            // to say 44 - below Google's recommended 48 dp and below the
            // measure this project uses everywhere else. Writing a number
            // out by hand leaves it quietly behind when the theme changes.
            ok.style.minHeight = Theme.Touch;
            ok.style.marginLeft = Theme.Gap;
            ok.style.flexShrink = 0;
            box.Add(ok);

            return box;
        }
    }
}
