# -*- coding: utf-8 -*-
"""
Arapca ARAYUZ metinleri. loc_ar.py bunu okuyor.

MODERN STANDART ARAPCA (fusha) - bkz. loc_ar.py.

YER TUTUCULAR {0} {1} olarak KALIYOR. Arapca sagdan sola akiyor ama
yer tutucunun KENDISI kod tarafinda; cumledeki yerini Arapca soz dizimi
belirliyor, Ingilizce'deki sirasi degil.

SAYILAR BATI RAKAMLARIYLA (0-9). Arap-Hindi rakamlari (٠١٢) fontta var
ama oyunun butun sayilari tek bicimde olmali: kasa, fiyat, gun sayisi
kod tarafindan bicimlenip geliyor ve o bicimleyici Bati rakami uretiyor.
Ikisini karistirmak, ayni ekranda iki ayri rakam sistemi demekti.
"""

UI = {
    # --- nisanlar ---------------------------------------------------------
    "badge.book_closed": "أُغلق الدفتر",
    "badge.book_closed.note": "حصّلت كل دَين كتبته.",
    "badge.first_beat": "صاروا يعرفونك",
    "badge.first_beat.note": "انفتحت حكاية زبون دائم لأول مرة.",
    "badge.first_expand": "وسّعت المحل",
    "badge.first_expand.note": "ارتقيت مستوى لأول مرة: طاولات أكثر، وإيجار أكثر.",
    "badge.first_ten_k": "عشرة آلاف في الصندوق",
    "badge.first_ten_k.note": "تجاوز الصندوق عشرة آلاف لأول مرة.",
    "badge.full_house": "لم يخرج أحد جائعًا",
    "badge.full_house.note": "في يوم ذروة لم تُردّ أحدًا ولم يغادر أحد غاضبًا.",
    "badge.renowned": "المطعم الذي يتحدث عنه الناس",
    "badge.renowned.note": "بلغت السمعة 90.",
    "badge.short_peak": "أدرت الذروة بشخص أقل",
    "badge.short_peak.note": "عملت بأقل من الطاقم اللازم ومع ذلك لم يغادر أحد غاضبًا.",

    # --- bildirimler ------------------------------------------------------
    "notice.angry": "غادر زبون — {0}",
    "notice.credit_given": "كُتب في الدفتر: {0}",
    "notice.credit_lost": "ضاع الدَين: {0}",
    "notice.credit_paid": "حُصّل الدَين: {0}",
    "notice.debt": "صار الصندوق بالسالب: {0}",
    "notice.downsized": "صغُر المحل — بقيت {0} طاولة.",
    "notice.equipment": "تمت ترقية {0} — المستوى {1}",
    "notice.equipment_sold": "بيع لتغطية الدَين: {0} › المستوى {1}",
    "notice.level_up": "ارتقى {0} إلى المستوى {1}",
    "notice.plates_out": "لا صحون نظيفة — المطبخ ينتظر. {0} صحنًا متسخًا عند المغسلة.",
    "notice.plates_out_busy": "لا صحون نظيفة — غسّال الصحون لا يلحق. {0} صحنًا متسخًا عند المغسلة.",
    "notice.regular": "وصل {0}.",
    "notice.regular_upset": "انزعج {0} — لن يأتي {1} أيام.",
    "notice.rejected": "لا يمكن فعل هذا الآن.",
    "notice.rejected_book": "امتلأ الدفتر — حصّل أولًا.",
    "notice.rejected_budget": "يكفي لليوم — تابع غدًا.",
    "notice.rejected_cash": "لا يوجد نقد كافٍ في الصندوق.",
    "notice.requested": "طُلب ولم يكن متوفرًا: {0}",
    "notice.resigned": "ترك {0} العمل.",
    "notice.rushed": "استعجل {0} — {1} طلبات",
    "notice.save_failed": "تعذّر حفظ اللعبة — تحقق من مساحة التخزين في جهازك.",
    "notice.service_done": "انتهى الدوام — يمكنك إغلاق اليوم.",
    "notice.storage": "تمت ترقية غرفة التبريد — المستوى {0}",
    "notice.tenure_lokanta": "مضى على {0} هنا {1} يومًا. لم يعد يحتاج أن يسأل.",
    "notice.tenure_zincir": "أتمّ {0} {1} يومًا من الورديات. الجدد يسألون عنه.",
    "notice.turned_away": "انصرفت مجموعة — لا شيء في اللائحة يمكن تحضيره",
    "notice.unknown": "غير معروف",
    "notice.unlocked": "طبق جديد متاح: {0}",
    "notice.wages_late": "تأخرت الأجور — ينقص {0}.",
    "notice.weekly": "دفعت {0} إيجارًا و{1} أجورًا.",
    "notice.why.food": "لم يصل الطعام",
    "notice.why.order": "لم يأخذ أحد الطلب",
    "notice.why.table": "لم يجد طاولة",
    "notice.why.other": "لم يستطع الانتظار",

    # --- yil sonu eksenleri -----------------------------------------------
    "score.axis.combo": "نسبة الوجبات المجمّعة",
    "score.axis.credit": "الديون المحصّلة",
    "score.crew": "الفريق",
    "score.place": "المكان",
    "score.regulars": "الزبائن الدائمون",
    "score.reputation": "السمعة",
    "score.resilience": "المتانة",
    "score.signature": "المطبخ",
    "score.wealth": "الثروة",

    # --- ortak ------------------------------------------------------------
    "ui.badge.earned": "وسام جديد",
    "ui.badge.have": "مُحرز",
    "ui.badge.open": "ليس بعد",
    "ui.badge.progress": "{0} / {1}",
    "ui.badge.title": "الأوسمة",
    "ui.common.cancel": "إلغاء",
    "ui.common.coin": "¤",
    "ui.common.ok": "حسنًا",
    "ui.common.tier": "المستوى",
    "ui.common.top_tier": "أعلى مستوى",
    "ui.common.upgrade": "ترقية — {0}",
    "ui.common.yes": "نعم",

    # --- yapimci ----------------------------------------------------------
    "ui.credits.audio": "الموسيقى والصوت",
    "ui.credits.audio_by": "مُولّدة داخل اللعبة",
    "ui.credits.author": "Ahmet Caner Akar",
    "ui.credits.design": "التصميم والبرمجة والمحتوى",
    "ui.credits.font": "الخط",
    "ui.credits.font_by": "Rubik + Noto Sans SC — SIL OFL 1.1",
    "ui.credits.font_copyright": "Copyright 2015 The Rubik Project Authors · Copyright 2014-2021 Adobe (Noto Sans SC)",
    "ui.credits.licenses": "تراخيص المصادر المفتوحة",
    "ui.credits.models": "المجسّمات ثلاثية الأبعاد",
    "ui.credits.models_by": "Kenney (kenney.nl) — CC0",

    # --- mutfak secimi ----------------------------------------------------
    "ui.cuisine.combo": "الوجبة المجمّعة: أبقِ ثلاثة أطباق معًا في اللائحة فترتفع الفاتورة — ويرتفع حِمل المطبخ كذلك.",
    "ui.cuisine.credit": "الدفتر: يرهق السيولة، ويبني الوفاء.",
    "ui.cuisine.fastfood_desc": "إيقاع سريع، فواتير صغيرة، زحام. اللائحة تبقى قصيرة.",
    "ui.cuisine.pick": "بأي مطبخ تبدأ؟",
    "ui.cuisine.signature": "الميزة المميّزة",
    "ui.cuisine.start": "ابدأ",
    "ui.cuisine.turk_desc": "ذروة غداء قوية، فواتير كبيرة، زبائن من الحي.",

    # --- yil sonu ---------------------------------------------------------
    "ui.end.continue": "تابع في اللعب الحر",
    "ui.end.lede": "أدرته {0} يومًا. نتيجتك في نهاية السنة: {1} / 100.",
    "ui.end.menu": "القائمة الرئيسية",
    "ui.end.plaque0": "مطعم صمد",
    "ui.end.plaque1": "مطعم الحي",
    "ui.end.plaque2": "مطعم سمع به الناس",
    "ui.end.plaque3": "المطعم الذي تتحدث عنه المدينة",

    # --- hata -------------------------------------------------------------
    "ui.error.content": "تعذّر قراءة ملفات المحتوى. هذا خطأ في المحتوى؛ واللعبة لا تفتح بتوازن ناقص.",
    "ui.error.save": "تعذّر فتح الحفظ.",
    "ui.error.title": "تعذّر تشغيل اللعبة",

    # --- aksam raporu -----------------------------------------------------
    "ui.evening.away": "لن يمرّ لفترة.",
    "ui.evening.gross": "الربح الإجمالي",
    "ui.evening.hall": "الصالة",
    "ui.evening.in_book": "في الدفتر",
    "ui.evening.ingredients": "المكوّنات",
    "ui.evening.left_table": "غادر الطاولة",
    "ui.evening.lost": "الخسائر",
    "ui.evening.low_morale": "{0} من الفريق معنوياتهم منخفضة — قد يتركون العمل",
    "ui.evening.money": "المال",
    "ui.evening.next": "اليوم التالي",
    "ui.evening.next_sub": "إلى اليوم {0}",
    "ui.evening.profit": "ربح اليوم",
    "ui.evening.regulars": "الزبائن الدائمون",
    "ui.evening.rent": "الإيجار المدفوع",
    "ui.evening.rent_in": "{1} بعد {0} أيام",
    "ui.evening.rent_next": "الإيجار القادم",
    "ui.evening.revenue": "الإيرادات",
    "ui.evening.same": "كما أمس",
    "ui.evening.satisfaction": "الرضا",
    "ui.evening.served_n": "{0} زبونًا / {1} طاولة",
    "ui.evening.spoiled": "التالف",
    "ui.evening.title": "تقرير اليوم",
    "ui.evening.turned_away": "مردودون",
    "ui.evening.visits": "{0} زيارة",
    "ui.evening.wages": "الأجور المدفوعة",

    # --- genisleme --------------------------------------------------------
    "ui.expand.buy": "توسيع — {0}",
    "ui.expand.last": "أنت في المستوى الأخير.",
    "ui.expand.tables": "الطاولات",
    "ui.expand.title": "التوسيع",
    "ui.expand.warn": "الإيجار يرتفع أيضًا — والطاولات الفارغة خسارة.",

    "ui.game.title": "Lokanta",

    # --- ipuclari ---------------------------------------------------------
    "ui.hint.cap": "بهذا العدد من الطاولات تبلغ سمعتك {0} على الأكثر. لتصعد أكثر تحتاج صالة أكبر.",
    "ui.hint.interventions": "التدخلات الثلاثة من جيب واحد: {0} في اليوم. وما لا تنفقه يضيع عند الإغلاق.",
    "ui.hint.menu": "إن خلت اللائحة عاد الزبائن من الباب. وتقرير اليوم يبيّن كم منهم.",
    "ui.hint.ok": "فهمت",
    "ui.hint.price": "أنت تحدّد السعر. ما يفوق السوق كثيرًا يطرد الزبائن، وما يقلّ عنه كثيرًا يأكل ربحك.",
    "ui.hint.rent": "الإيجار مستحق غدًا. إن لم يكفِ الصندوق وقعت في دَين.",
    "ui.hint.select": "المس الصالة ثم المس طاولة: ما تقدّمه يذهب إلى تلك الطاولة.",
    "ui.hint.service": "بعد فتح الدوام لا يمكنك الشراء حتى المساء. جهّز مخزونك ولائحتك الآن.",
    "ui.hint.staff": "الطاقم يمنحك طاقة لكنه يكلّف أجورًا كل أسبوع. انظر إلى الصندوق قبل التوظيف.",

    # --- servis ekrani ustu -----------------------------------------------
    "ui.hud.angry": "المنصرفون",
    "ui.hud.back": "رجوع",
    "ui.hud.cash": "النقد",
    "ui.hud.free_play": "لعب حر",
    "ui.hud.menu": "إيقاف",
    "ui.hud.pause": "إيقاف",
    "ui.hud.plates": "صحون نظيفة",
    "ui.hud.rent_in": "الإيجار بعد {0} أيام — {1}",
    "ui.hud.rent_today": "الإيجار مستحق اليوم — {0}",
    "ui.hud.reputation": "السمعة",
    "ui.hud.resume": "متابعة",
    "ui.hud.satisfaction": "الرضا",
    "ui.hud.season": "اليوم {0} من {1}",
    "ui.hud.served": "من خدمتهم",
    "ui.hud.speed": "السرعة",
    "ui.hud.tables": "الطاولات",
    "ui.hud.today": "اليوم",

    # --- defter -----------------------------------------------------------
    "ui.ledger.amount": "المبلغ",
    "ui.ledger.chance_now": "إن طالبت الآن",
    "ui.ledger.chance_wait": "إن انتظرت",
    "ui.ledger.chase": "طالِب الآن",
    "ui.ledger.days": "{0} أيام",
    "ui.ledger.due": "الاستحقاق",
    "ui.ledger.empty": "الدفتر نظيف.",
    "ui.ledger.had_tea": "قُدّم الشاي حين فُتح هذا الدَين.",
    "ui.ledger.note": "المطالبة المبكرة تنصّف الاحتمال، وإن أخفقت أُغلق الدَين نهائيًا.",
    "ui.ledger.title": "الدفتر",
    "ui.ledger.today": "اليوم",
    "ui.ledger.total": "{0} في الدفتر",

    # --- kredi ------------------------------------------------------------
    "ui.loan.installment": "القسط الأسبوعي",
    "ui.loan.one_at_a_time": "لا يمكنك حمل أكثر من قرض واحد في الوقت نفسه.",
    "ui.loan.open": "لديك قرض قائم",
    "ui.loan.repay": "إجمالي السداد",
    "ui.loan.take": "خذه",
    "ui.loan.title": "قرض",
    "ui.loan.warning": "ينضمّ القسط إلى تكاليفك الأسبوعية. وإن تخلّفت عنه صغُر المحل.",
    "ui.loan.weekly": "تكلفتك الثابتة الأسبوعية {0}",
    "ui.loan.weeks_left": "الأسابيع المتبقية",

    # --- menu ekrani ------------------------------------------------------
    "ui.menu.add": "أضف إلى اللائحة",
    "ui.menu.continue": "متابعة",
    "ui.menu.cost": "الكلفة",
    "ui.menu.credits": "صنّاع اللعبة",
    "ui.menu.favourite_of": "{0} يحب هذا الطبق",
    "ui.menu.group_locked": "مقفل",
    "ui.menu.group_on": "في اللائحة",
    "ui.menu.group_open": "متاحة — يمكنك إضافتها",
    "ui.menu.group_soon": "قريبًا",
    "ui.menu.locked": "مقفل",
    "ui.menu.margin": "الهامش",
    "ui.menu.needs_equipment": "يحتاج {0}",
    "ui.menu.needs_reputation": "يحتاج سمعة {0}",
    "ui.menu.new": "لعبة جديدة",
    "ui.menu.onmenu": "في اللائحة",
    "ui.menu.price": "السعر",
    "ui.menu.quit": "خروج",
    "ui.menu.settings": "الإعدادات",
    "ui.menu.subtitle": "كل ما في اللائحة يُبقى له مخزون.",
    "ui.menu.tagline": "أنت صاحب المحل، لا الطبّاخ.",
    "ui.menu.unlock_day": "يُفتح في اليوم {0}",
    "ui.menu.vs_market": "مقابل السوق",

    # --- sabah ------------------------------------------------------------
    "ui.morning.average_over": "أعلى من المتوسط بـ {0}%",
    "ui.morning.average_same": "سعر متوسط",
    "ui.morning.average_under": "أقل من المتوسط بـ {0}%",
    "ui.morning.buy_days": "مخزون {0} أيام — {1}",
    "ui.morning.cheap": "رخيص اليوم",
    "ui.morning.checklist": "تحققات الافتتاح",
    "ui.morning.days_keep": "يومًا متبقيًا",
    "ui.morning.equipment": "المعدّات",
    "ui.morning.expensive": "غالٍ اليوم",
    "ui.morning.loan": "قرض",
    "ui.morning.market": "السوق",
    "ui.morning.menu": "اللائحة",
    "ui.morning.never_spoils": "لا يفسد",
    "ui.morning.no_storage": "بلا غرفة تبريد، كل ما يزيد عن مخزون يوم واحد يضيع حتى الصباح.",
    "ui.morning.open": "افتح الدوام",
    "ui.morning.open_sub": "يبدأ اليوم {0}",
    "ui.morning.quality": "جودة المكوّنات",
    "ui.morning.quality_down": "أطباق لائحتك تُرضي الزبائن أقل بـ {0} نقطة.",
    "ui.morning.quality_none": "لا أطباق في اللائحة.",
    "ui.morning.quality_up": "أطباق لائحتك تُرضي الزبائن أكثر بـ {0} نقطة.",
    "ui.morning.ready_cooks": "{0} في المطبخ",
    "ui.morning.ready_menu": "{0} طبقًا في اللائحة",
    "ui.morning.ready_stock_ok": "المخزون يكفي اليوم",
    "ui.morning.ready_stock_part": "المخزون يكفي {0} من {1} زبونًا",
    "ui.morning.ready_warn_cook": "لا طبّاخ في المطبخ. اضغط ثانية لتفتح رغم ذلك.",
    "ui.morning.ready_warn_menu": "لا شيء في اللائحة. اضغط ثانية لتفتح رغم ذلك.",
    "ui.morning.ready_warn_stock": "المخزون لن يكفي اليوم. اضغط ثانية لتفتح رغم ذلك.",
    "ui.morning.restock": "اشترِ المخزون المقترح",
    "ui.morning.spoils_tonight": "يضيع حتى الصباح",
    "ui.morning.staff": "الطاقم",
    "ui.morning.stock": "المخزون",
    "ui.morning.storage_none": "بلا تبريد — كل ما يفسد يضيع الليلة",
    "ui.morning.storage_tier": "التبريد المستوى {0}",

    # --- duraklatma -------------------------------------------------------
    "ui.pause.resume": "متابعة",
    "ui.pause.save_quit": "احفظ واخرج",
    "ui.pause.season": "حصاد نهاية السنة",

    "ui.phase.evening": "المساء",
    "ui.phase.morning": "الصباح",
    "ui.phase.service": "الدوام",

    "ui.quality.0": "منخفضة",
    "ui.quality.1": "عادية",
    "ui.quality.2": "عالية",

    # --- servis -----------------------------------------------------------
    "ui.service.attention": "اهتمام",
    "ui.service.close": "أغلق اليوم",
    "ui.service.close_sub": "انتهى الدوام",
    "ui.service.combo_off": "الوجبة المجمّعة مغلقة",
    "ui.service.combo_on": "الوجبة المجمّعة مفتوحة",
    "ui.service.credit": "دفتر",
    "ui.service.crisis": "نفد صبرهم تقريبًا",
    "ui.service.done_care": "اهتممت بالطاولة {0}",
    "ui.service.done_care_any": "تم الاهتمام",
    "ui.service.done_credit": "كُتب {0} في الدفتر",
    "ui.service.done_rush": "تم تسريع {0}",
    "ui.service.done_tea": "قُدّم الشاي للطاولة {0}",
    "ui.service.done_tea_any": "قُدّم الشاي",
    "ui.service.done_tea_room": "أُرسل الشاي إلى الصالة",
    "ui.service.guest": "زبون",
    "ui.service.none_credit": "لا أحد يطلب الدفتر",
    "ui.service.none_station": "لا قسم متعثّر",
    "ui.service.none_table": "لا طاولة تنتظر",
    "ui.service.none_waiting": "لا طاولة تنتظر",
    "ui.service.running_sub": "الدوام جارٍ",
    "ui.service.rush": "تسريع",
    "ui.service.table_n": "الطاولة {0}",
    "ui.service.target_auto": "الأسوأ حالًا",
    "ui.service.tea": "شاي",

    # --- ayarlar ----------------------------------------------------------
    "ui.settings.back": "رجوع",
    "ui.settings.hints_reset": "أظهر التلميحات من جديد",
    "ui.settings.language": "اللغة",
    "ui.settings.music": "الموسيقى",
    "ui.settings.sound": "الصوت",
    "ui.settings.title": "الإعدادات",

    # --- kayit yuvasi -----------------------------------------------------
    "ui.slot.broken": "حفظ تالف",
    "ui.slot.day": "اليوم {0}",
    "ui.slot.delete": "حذف",
    "ui.slot.delete_confirm": "أتحذف هذا الحفظ؟ لا يمكن التراجع.",
    "ui.slot.empty": "فارغ",
    "ui.slot.overwrite": "أتكتب فوق هذه الخانة؟",
    "ui.slot.title": "خانة الحفظ",
    "ui.slot.unloadable": "لا يمكن تحميله",

    # --- personel ---------------------------------------------------------
    "ui.staff.busser": "جامع الصواني",
    "ui.staff.candidates": "المتقدّمون",
    "ui.staff.cap": "حدّ الطاقم",
    "ui.staff.cap_full": "اكتمل الطاقم",
    "ui.staff.cook": "المطبخ",
    "ui.staff.days": "{0} ({1} يومًا)",
    "ui.staff.fire": "الاستغناء عنه",
    "ui.staff.fire_confirm": "أتستغني عن هذا الشخص؟ خبرته تعود إلى الصفر.",
    "ui.staff.hire": "توظيف",
    "ui.staff.inherited": "سيّئ المزاج — الطبّاخ الذي ورثته",
    "ui.staff.level": "المستوى",
    "ui.staff.morale": "المعنويات",
    "ui.staff.no_candidate": "لم يبقَ متقدّمون. تتجدّد القائمة كل ثلاثة أيام.",
    "ui.staff.normal": "عادي",
    "ui.staff.salon": "الصالة",
    "ui.staff.salon_needed": "لا أحد في الصالة — تحتاج {0} اليوم.",
    "ui.staff.salon_none": "لا أحد في الصالة. بعدد طاولات اليوم لا حاجة لأحد.",
    "ui.staff.sink": "نوبة المغسلة",
    "ui.staff.sink_add": "أرسِله إلى المغسلة",
    "ui.staff.sink_hint": "من يقف عند المغسلة لا يخدم الزبائن. وإن لم يقف أحد، ينتظر المطبخ حين تنفد الصحون النظيفة.",
    "ui.staff.sink_n": "{0} عند المغسلة",
    "ui.staff.sink_none": "لا أحد عند المغسلة — يتدخّل أحد من الصالة حين تتكدّس الصحون",
    "ui.staff.sink_remove": "أعِده إلى الصالة",
    "ui.staff.to_serve_all": "لخدمة الجميع",
    "ui.staff.wage": "الأجر",
    "ui.staff.weekend": "عطلة الأسبوع",

    # --- istasyon ---------------------------------------------------------
    "ui.station.cuisine_only": "لهذا المطبخ فقط",
    "ui.station.slots": "المواقع",
    "ui.station.too_low": "لا يكفي لهذا العدد من الطاولات",

    "ui.storage.desc": "يستعيد جزءًا من عمر المواد سريعة التلف.",
    "ui.story.continue": "متابعة",

    "ui.week.note": "مقابل الأسبوع الماضي",
    "ui.week.title": "الأسبوع {0}",
}
