# -*- coding: utf-8 -*-
"""
Ingilizce ARAYUZ metinleri. loc_en.py bunu okuyor.

Icerik metinlerinden (yemek, malzeme, musteri) ayri tutuluyor cunku
kaynaklari ayri: icerik metinleri content/*.json'dan turiyor, bunlar
elle yaziliyor.

BICIMLEME YER TUTUCULARI ({0}, {1}) AYNEN korunuyor. Uretec ikisinde de
ayni yer tutucularin bulundugunu dogruluyor: eksik bir {0} calisma
aninda bicimleme hatasi degil, SESSIZ bir eksik metin veriyor.
"""

UI = {
    "ui.game.title": "Lokanta",
    "ui.menu.new": "New Game",
    "ui.menu.continue": "Continue",
    "ui.menu.settings": "Settings",
    "ui.menu.quit": "Quit",
    "ui.menu.credits": "Credits",

    "ui.cuisine.pick": "Which kitchen are you starting with?",
    "ui.cuisine.start": "Start",
    "ui.cuisine.signature": "Signature mechanic",
    "ui.cuisine.combo": "Combo: keep three dishes on the menu together and the "
                        "bill grows — so does the kitchen's load.",
    "ui.cuisine.credit": "Running a tab: hurts your cash flow, builds loyalty.",

    "ui.hud.menu": "Pause",
    "ui.hud.season": "Day {0} of {1}",
    "ui.hud.free_play": "free play",
    "ui.slot.title": "Save slot",
    "ui.slot.empty": "Empty",
    "ui.slot.unloadable": "Cannot be loaded",
    "ui.slot.day": "Day {0}",
    "ui.slot.delete": "Delete",
    "ui.slot.delete_confirm": "Delete this save? It cannot be undone.",
    "ui.slot.overwrite": "Overwrite this slot?",

    "ui.phase.morning": "Morning",
    "ui.phase.service": "Service",
    "ui.phase.evening": "Evening",

    "ui.hud.cash": "Cash",
    "ui.hud.reputation": "Reputation",
    "ui.hud.tables": "Tables",
    "ui.hud.served": "Served",
    # Yeni arayuz. Etiketler KISA: kart dar, dugme alt satiri tek satir.
    "ui.hud.today": "Today",
    "ui.hud.satisfaction": "Satisfaction",
    "ui.morning.checklist": "Opening checks",
    "ui.morning.open_sub": "Day {0} begins",
    "ui.service.close_sub": "Service is over",
    "ui.service.running_sub": "Service running",
    "ui.service.combo_on": "Combo on",
    "ui.service.combo_off": "Combo off",
    "ui.evening.next_sub": "On to day {0}",
    # Aksam seridi sarip tasiyordu: Ingilizce'de 230 dp, butce 220
    # (Turkce 199). Sikisik bir ozette etiket KISA olmali - "Walked
    # out" iki kelime ve iki satir demek.
    "ui.hud.angry": "Walkouts",
    "ui.service.none_station": "No station is backed up",
    "ui.service.none_table": "No table is waiting",
    "ui.service.none_credit": "Nobody is asking for credit",
    "ui.service.done_rush": "{0} sped up",
    "ui.service.done_tea": "Tea served at table {0}",
    "ui.service.done_tea_any": "Tea served",
    "ui.service.done_tea_room": "Tea sent to the room",
    "ui.service.none_waiting": "No table is waiting",
    "ui.service.done_care": "Table {0} got your attention",
    "ui.service.done_care_any": "Attention given",
    "ui.service.done_credit": "{0} written in the book",
    "ui.service.guest": "Guest",
    "ui.hud.back": "Back",
    "ui.hud.pause": "Pause",
    "ui.hud.resume": "Resume",
    "ui.hud.speed": "Speed",

    "ui.morning.market": "Market",
    "ui.morning.menu": "Menu",
    "ui.morning.staff": "Crew",
    "ui.morning.equipment": "Equipment",
    "ui.morning.open": "Open service",
    "ui.morning.loan": "Loan",
    "ui.loan.title": "Loan",
    "ui.loan.weekly": "Your weekly fixed cost is {0}",
    "ui.loan.repay": "Total repayment",
    "ui.loan.installment": "Weekly instalment",
    "ui.loan.weeks_left": "Weeks left",
    "ui.loan.take": "Take it",
    "ui.loan.open": "You have a loan running",
    "ui.loan.one_at_a_time": "You can only carry one loan at a time.",
    "ui.loan.warning": "The instalment joins your weekly costs. Miss it and the "
                       "place shrinks.",

    "ui.hint.service": "Once service opens you cannot shop until evening. Get "
                       "your stock and menu ready now.",
    "ui.hint.menu": "With nothing on the menu, guests turn round at the door. "
                    "The day report shows how many did.",
    "ui.hint.interventions": "All three interventions share one purse: {0} a day. "
                             "Unspent, they are gone when the day ends.",
    "ui.hint.rent": "Rent is due tomorrow. If the till is short, you go into debt.",
    "ui.hint.price": "You set the price. Far above the market drives guests away; "
                     "far below eats your profit.",
    "ui.hint.staff": "Crew gives you capacity but costs wages every week. Check "
                     "the till before you hire.",
    "ui.hint.select": "Tap the room, then tap a table: what you offer goes to "
                      "that table.",
    "ui.hint.cap": "At this many tables your reputation can reach {0} at most. "
                   "To go higher you need a bigger dining room.",
    "ui.hint.ok": "Got it",
    "notice.service_done": "Service is over — you can close the day.",
    "notice.save_failed": "Could not write the save — check your device storage.",
    "ui.settings.hints_reset": "Show the hints again",
    "ui.morning.buy_days": "{0} days of stock — {1}",
    "ui.morning.no_storage": "Without a cold store, anything beyond one day of "
                             "stock is gone by morning.",
    "ui.morning.restock": "Buy the suggested stock",
    "ui.morning.average_over": "{0}% above average",
    "ui.morning.average_under": "{0}% below average",
    "ui.morning.average_same": "Average price",
    "ui.morning.cheap": "Cheap today",
    "ui.morning.expensive": "Pricey today",
    "ui.morning.stock": "Stock",
    "ui.morning.days_keep": "days left",
    "ui.morning.spoils_tonight": "gone by morning",
    "ui.morning.never_spoils": "never spoils",
    "ui.menu.onmenu": "On the menu",
    "ui.service.crisis": "LOSING PATIENCE",
    "ui.service.table_n": "Table {0}",
    "ui.evening.same": "same as yesterday",
    "ui.morning.ready_menu": "{0} dishes on the menu",
    "ui.morning.ready_stock_ok": "Stock covers today",
    "ui.morning.ready_stock_part": "Stock covers {0} of {1} guests",
    "ui.morning.ready_cooks": "{0} in the kitchen",
    "ui.morning.ready_warn_menu": "Nothing on the menu. Press again to open anyway.",
    "ui.morning.ready_warn_cook": "No cook in the kitchen. Press again to open anyway.",
    "ui.morning.ready_warn_stock": "Stock will not last the day. Press again to "
                                   "open anyway.",
    "ui.menu.group_on": "ON THE MENU",
    "ui.menu.group_open": "AVAILABLE — you can add these",
    "ui.menu.group_soon": "COMING SOON",
    "ui.menu.group_locked": "Locked",
    "ui.menu.locked": "Locked",
    "ui.menu.needs_reputation": "Needs {0} reputation",
    "ui.menu.needs_equipment": "Needs {0}",
    "ui.menu.vs_market": "Against the market",
    "ui.menu.add": "Add to menu",
    "ui.menu.price": "Price",
    "ui.menu.cost": "Cost",
    "ui.menu.margin": "Margin",
    "ui.menu.favourite_of": "{0} loves this",
    "ui.staff.hire": "Hire",
    "ui.staff.fire": "Let go",
    "ui.staff.candidates": "Candidates",
    "ui.staff.morale": "Morale",
    "ui.staff.level": "Level",
    "ui.staff.wage": "Wage",
    "ui.staff.cook": "Kitchen",
    "ui.staff.salon": "Front of house",
    "ui.staff.fire_confirm": "Let this person go? Their experience resets.",
    "ui.staff.salon_none": "No front-of-house crew. At today's table count you "
                           "do not need any.",
    "ui.staff.salon_needed": "No front-of-house crew — you need {0} today.",
    "ui.staff.cap": "Crew limit",
    "ui.staff.to_serve_all": "To serve everyone",
    "ui.staff.weekend": "weekend",
    "ui.staff.sink": "Sink duty",
    "ui.staff.sink_none": "Nobody at the sink — someone from the floor steps in when the "
                          "plates pile up",
    "ui.staff.sink_n": "{0} on the sink",
    "ui.staff.sink_add": "Put on sink",
    "ui.staff.sink_remove": "Back to the floor",
    "ui.staff.sink_hint": "Whoever is at the sink is not serving. With nobody "
                          "there, the kitchen waits when the clean plates run out.",
    "ui.hud.plates": "Clean plates",
    "notice.plates_out": "Out of clean plates — the kitchen is waiting. "
                         "{0} dirty plates at the sink.",
    "notice.plates_out_busy": "Out of clean plates — the dishwasher cannot "
                              "keep up. {0} dirty plates at the sink.",
    "ui.staff.no_candidate": "No candidates left. The pool refreshes every three days.",
    "ui.staff.normal": "normal",
    "ui.service.close": "Close the day",
    "ui.service.rush": "Speed up",
    "ui.service.tea": "Tea",
    "ui.service.attention": "Attention",
    "ui.service.credit": "Tab",
    # "most impatient" (14) TR "sabırsız"dan (8) UZUN ve serit tam
    # sinirda: TR'de tasan kalip Ingilizce'de yeniden acilirdi.
    "ui.service.target_auto": "worst",
    "ui.evening.title": "Day report",
    "ui.evening.revenue": "Takings",
    "ui.evening.ingredients": "Ingredients",
    "ui.evening.profit": "Today's profit",
    "ui.evening.gross": "Gross profit",
    "ui.evening.rent_in": "{1} in {0} days",
    "ui.evening.rent_next": "Next rent",
    # Deger zaten bir ortalama ve baglami gun raporu: "Average"
    # kelimesi bilgi eklemeden iki satir aciyordu.
    "ui.evening.satisfaction": "Satisfaction",
    "ui.story.continue": "Continue",
    "ui.evening.next": "Next day",
    "ui.evening.spoiled": "Spoiled",
    "ui.evening.wages": "Wages paid",
    "ui.evening.rent": "Rent paid",
    "ui.end.continue": "Carry on in free play",
    "ui.end.menu": "Main Menu",
    "ui.settings.title": "Settings",
    "ui.settings.sound": "Sound",
    "ui.settings.music": "Music",
    "ui.settings.language": "Language",
    "ui.credits.licenses": "Open source licences",
    "ui.settings.back": "Back",
    "notice.angry": "A guest walked out — {0}",
    "notice.why.table": "could not get a table",
    "notice.why.order": "nobody took the order",
    "notice.why.food": "the food never came",
    "notice.why.other": "could not wait",
    "notice.turned_away": "A group walked away — nothing on the menu could be made",
    "notice.requested": "Asked for, not available: {0}",
    "notice.unlocked": "New dish unlocked: {0}",
    "notice.regular": "{0} is here.",
    "notice.regular_upset": "{0} is put out — away for {1} days.",
    "notice.resigned": "{0} has left.",
    "notice.level_up": "{0} levelled up: {1}",
    "notice.weekly": "Paid {0} rent and {1} wages.",
    "notice.wages_late": "Wages are late — {0} short.",
    "notice.debt": "The till has gone negative: {0}",
    "notice.credit_given": "Put on the tab: {0}",
    "notice.credit_paid": "Tab collected: {0}",
    "notice.credit_lost": "Tab written off: {0}",
    "notice.equipment": "{0} upgraded — tier {1}",
    "notice.storage": "Cold store upgraded — tier {0}",
    "notice.rushed": "{0} pushed — {1} orders",
    "notice.equipment_sold": "Sold to cover debt: {0} › tier {1}",
    "notice.downsized": "The place has shrunk — {0} tables left.",
    "notice.rejected": "That cannot be done right now.",
    "notice.rejected_cash": "Not enough cash in the till.",
    "notice.rejected_budget": "That is enough for today — carry on tomorrow.",
    "notice.rejected_book": "The book is full — collect first.",
    "notice.unknown": "unknown",
    "ui.end.plaque0": "A restaurant that survived",
    "ui.end.plaque1": "The neighbourhood's restaurant",
    "ui.end.plaque2": "A restaurant people have heard of",
    "ui.end.plaque3": "The restaurant this city talks about",
    "ui.end.lede": "You ran it for {0} days. Your year-end score: {1} / 100.",
    "ui.week.title": "Week {0}",
    "ui.week.note": "Against last week",
    "ui.badge.earned": "New mark",
    "ui.badge.title": "Marks",
    "ui.badge.progress": "{0} / {1}",
    "ui.badge.have": "earned",
    "ui.badge.open": "not yet",
    "badge.full_house": "Nobody left hungry",
    "badge.full_house.note": "On a peak day nobody was turned away and nobody walked out angry.",
    "badge.short_peak": "You ran the peak one short",
    "badge.short_peak.note": "You worked below the crew you needed and still nobody left angry.",
    "badge.book_closed": "The book is closed",
    "badge.book_closed.note": "You collected every tab you wrote.",
    "badge.first_beat": "They know you now",
    "badge.first_beat.note": "A regular's story opened for the first time.",
    "badge.first_expand": "You made the place bigger",
    "badge.first_expand.note": "You took a tier up for the first time - more tables, more rent.",
    "badge.renowned": "The restaurant people talk about",
    "badge.renowned.note": "Reputation reached 90.",
    "badge.first_ten_k": "Ten thousand in the till",
    "badge.first_ten_k.note": "The till passed ten thousand for the first time.",
    "ui.staff.busser": "Busser",
    "score.wealth": "Wealth",
    "score.reputation": "Reputation",
    "score.regulars": "Regulars",
    "score.crew": "Crew",
    "score.place": "The place",
    "score.resilience": "Resilience",
    "score.signature": "Kitchen",
    "score.axis.combo": "Combo share",
    "score.axis.credit": "Tabs collected",
    "ui.hud.rent_in": "Rent in {0} days — {1}",
    "ui.hud.rent_today": "Rent due today — {0}",
    "ui.pause.resume": "Resume",
    "ui.pause.season": "Year-End Review",
    "ui.pause.save_quit": "Save and quit",
    "ui.common.yes": "Yes",
    "ui.common.cancel": "Cancel",
    "ui.common.ok": "OK",
    "ui.common.coin": "¤",

    "ui.evening.money": "Money",
    "ui.evening.in_book": "On the book",
    "ui.ledger.title": "The book",
    "ui.ledger.total": "{0} on the book",
    "ui.ledger.empty": "The book is clean.",
    "ui.ledger.amount": "Amount",
    "ui.ledger.due": "Due",
    "ui.ledger.days": "{0} days",
    "ui.ledger.today": "today",
    "ui.ledger.chance_wait": "If you wait",
    "ui.ledger.chance_now": "If you chase now",
    "ui.ledger.had_tea": "Tea was served when this tab was opened.",
    "ui.ledger.chase": "Chase now",
    "ui.ledger.note": "Chasing halves the odds, and a miss closes the tab for good.",
    "ui.evening.hall": "Dining room",
    "ui.evening.turned_away": "Turned away",
    "ui.evening.lost": "Lost",
    "ui.evening.left_table": "Left the table",
    "ui.evening.regulars": "Regulars",
    "ui.evening.away": "Won't be by for a while.",
    "ui.evening.served_n": "{0} guests / {1} tables",
    "ui.evening.visits": "{0} visits",

    "ui.error.title": "The game could not start",
    "ui.error.content": "The content files could not be read. This is a "
                        "content error; the game refuses to open with a "
                        "broken balance.",
    "ui.error.save": "The save could not be opened.",
    "ui.menu.tagline": "You are the owner, not the cook.",
    "ui.slot.broken": "broken save",

    "ui.credits.design": "Design, code and content",
    "ui.credits.author": "Ahmet Caner Akar",
    "ui.credits.models": "3D models",
    "ui.credits.models_by": "Kenney (kenney.nl) — CC0",
    "ui.credits.audio": "Music and sound",
    "ui.credits.audio_by": "Synthesised in-game",
    "ui.credits.font": "Typeface",
    "ui.credits.font_by": "Rubik — SIL OFL 1.1",
    "ui.credits.font_copyright": "Copyright 2015 The Rubik Project Authors",

    "ui.cuisine.fastfood_desc": "Fast flow, small tickets, crowds. "
                                "The menu stays narrow.",
    "ui.cuisine.turk_desc": "Hard lunch peak, big tickets, neighbourhood "
                            "regulars.",

    "ui.staff.cap_full": "Crew is full",
    "ui.storage.desc": "Buys back part of the shelf life of perishables.",
    "ui.common.tier": "Tier",
    "ui.common.upgrade": "Upgrade — {0}",
    "ui.common.top_tier": "Top tier",
    "ui.station.cuisine_only": "cuisine only",
    "ui.station.slots": "Slots",
    "ui.station.too_low": "Too small for this many tables",
    "ui.expand.title": "Expansion",
    "ui.expand.last": "You are at the last tier.",
    "ui.expand.tables": "Tables",
    "ui.expand.warn": "Rent grows too — empty tables mean losses.",
    "ui.expand.buy": "Expand — {0}",
    "ui.evening.low_morale": "{0} on the crew have low morale — they may quit",
    "ui.morning.quality": "Ingredient quality",
    "ui.quality.0": "Low",
    "ui.quality.1": "Standard",
    "ui.quality.2": "High",
    "ui.morning.quality_none": "No dishes on the menu.",
    "ui.morning.quality_up": "Dishes on your menu please guests {0} points more.",
    "ui.morning.quality_down": "Dishes on your menu please guests {0} points less.",
    "ui.morning.storage_tier": "Cold storage tier {0}",
    "ui.morning.storage_none": "No cold storage — anything perishable goes tonight",
    "ui.menu.subtitle": "Everything on the menu is kept in stock.",
    "ui.menu.unlock_day": "Opens on day {0}",
    "ui.staff.days": "{0} ({1} days)",
    "ui.staff.inherited": "Cranky — the cook you inherited",
}
