using Lokanta.Content;
using Lokanta.Core.Content;
using Lokanta.Core.Economy;
using Lokanta.Core.Save;
using Lokanta.Core.Sim;
using Xunit;
using Xunit.Abstractions;

namespace Lokanta.Core.Tests
{
    /// <summary>
    /// Station slots and equipment. docs/27-time-model.md Decision D:
    ///   - prepMs is the dish's WALL CLOCK time
    ///   - the cook is tied up for prepMs x attendBp / 10000
    ///   - an upgrade either adds a slot or lowers attendBp; it never touches
    ///     prepMs
    ///
    /// This file verifies that the decision is implemented and that the equipment
    /// makes a MEASURABLE difference. The equipment prices come from
    /// content/equipment.json and that file is generated by tools/balance.
    /// </summary>
    public class EquipmentTests
    {
        private readonly ITestOutputHelper _out;
        public EquipmentTests(ITestOutputHelper output) { _out = output; }

        private const ulong Seed = 20260910UL;

        private static EconomyConfig Economy() => ContentLoader.LoadEconomy(Paths.Content);
        private static ContentSet Content() => ContentSetLoader.Load(Paths.Content, "fastfood");

        private static TimingConfig Timing()
        {
            ContentSet c = Content();
            return c.SlotDurationsBp != null
                ? TimingConfig.Default().WithSlotDurations(c.SlotDurationsBp).WithEatMs(c.EatMs)
                : TimingConfig.Default();
        }

        private static Simulation NewSim()
        {
            return new Simulation(Economy(), Content(), Timing(), Seed);
        }

        /// <summary>
        /// The first station this cuisine actually uses.
        ///
        /// NOT STATION 0. These tests used to buy index 0 on the assumption
        /// that it is the hob and the hob is always in use. It stopped being
        /// true the day fast food's fried dishes moved to a fryer of their own
        /// (18 September): every one of its hob dishes was deep fried, so the
        /// cuisine no longer uses the hob at all - and the simulation is right
        /// to refuse to sell equipment for a station nothing cooks on.
        ///
        /// A test that names a station by INDEX is a test that will break the
        /// next time the closed list grows in the middle. This asks the
        /// simulation.
        /// </summary>
        private static int UsedStation(Simulation sim) { return UsedStation(sim, 0); }

        /// <summary>The nth station this cuisine uses.</summary>
        private static int UsedStation(Simulation sim, int nth)
        {
            int seen = 0;
            for (int i = 0; i < sim.StationCount; i++)
            {
                if (!sim.IsStationUsed(i)) continue;
                if (seen == nth) return i;
                seen++;
            }
            throw new Xunit.Sdk.XunitException(
                "the cuisine uses fewer than " + (nth + 1) + " stations");
        }

        /// <summary>
        /// Buys stock at the market in the morning. Without this the kitchen is
        /// empty: in the warm-up run the reputation fell to zero and the
        /// measurement became meaningless.
        /// </summary>
        private static void Restock(Simulation sim)
        {
            for (int i = 0; i < sim.IngredientCount; i++)
            {
                int need = sim.RecommendedRestock(i);
                if (need > 0)
                    sim.Apply(new Command(sim.TickIndex, CommandKind.OrderIngredient, i, need));
            }
        }

        /// <summary>
        /// Narrows the menu to three main courses. A wide menu both splits the
        /// stock and lowers satisfaction; this is why in the warm-up run the
        /// reputation stuck at 27 and only 26 parties came to fourteen tables.
        /// </summary>
        private static void NarrowMenu(Simulation sim)
        {
            int mains = 0;
            for (int i = 0; i < sim.DishCount; i++)
            {
                if (!sim.IsUnlocked(i)) continue;
                bool on = !sim.IsMain(i) || mains++ < 3;
                sim.Apply(new Command(sim.TickIndex, CommandKind.SetMenuSlot, i, on ? 1 : 0));
            }
        }

        private static DayReport RunOneDay(Simulation sim)
        {
            Restock(sim);
            sim.Apply(new Command(sim.TickIndex, CommandKind.OpenService));
            int limit = Timing().ServiceTicks + 4000;
            for (int t = 0; t < limit; t++)
            {
                sim.Tick();
                if (sim.ServiceComplete) break;
            }
            sim.Apply(new Command(sim.TickIndex, CommandKind.CloseDay));
            return sim.BuildDayReport();
        }

        // ====================================================================
        [Fact]
        public void The_content_loads_the_shared_stations_and_their_ladders()
        {
            ContentSet c = Content();

            // The shared stations come FIRST and that order is binding: a
            // dish's StationIndex and the equipment tiers in the save file are
            // carried by index. The cuisine's own named equipment is appended
            // behind them (docs/09: 10 per cuisine).
            //
            // THE LIST IS ASKED OF THE LOADER, not copied here. It used to be
            // written out in this test as well, and when the fryer was added
            // between the hob and the grill (18 September) the test failed for
            // being out of date rather than for anything being wrong - which
            // is a test measuring its own copy of the answer.
            string[] want = Lokanta.Content.ContentSetLoader.StationIds;
            Assert.True(c.Stations.Length >= want.Length);
            for (int i = 0; i < want.Length; i++)
                Assert.Equal(want[i], c.Stations[i].Id);

            // The cuisine's own stations MUST BE BOUGHT: at least two rungs.
            for (int i = want.Length; i < c.Stations.Length; i++)
            {
                Assert.True(c.Stations[i].Tiers.Length >= 2, c.Stations[i].Id);
                Assert.True(c.Stations[i].Tiers[1].Price > 0, c.Stations[i].Id);
            }

            foreach (StationDef st in c.Stations)
            {
                Assert.True(st.Tiers.Length >= 2, st.Id + " has a one-rung ladder");
                Assert.Equal(0, st.Tiers[0].Price);              // the starting rung is free
                for (int t = 1; t < st.Tiers.Length; t++)
                {
                    Assert.True(st.Tiers[t].Price > st.Tiers[t - 1].Price,
                        st.Id + " t" + t + " price does not increase");
                    Assert.True(st.Tiers[t].Slots >= st.Tiers[t - 1].Slots,
                        st.Id + " t" + t + " slots decrease");
                    Assert.True(st.Tiers[t].AttendBp <= st.Tiers[t - 1].AttendBp,
                        st.Id + " t" + t + " attendBp increases");
                }
            }
        }

        [Fact]
        public void The_docs27_peak_slot_table_holds()
        {
            // docs/27 3.3: at the tier 4 peak the grill and the hob need 4 slots,
            // the oven 2 and the rest 1. The top of the ladder has to meet that.
            ContentSet c = Content();
            var want = new System.Collections.Generic.Dictionary<string, int>
            {
                { "ocak", 4 }, { "izgara", 4 }, { "firin", 2 },
                { "soguk", 1 }, { "icecek", 1 }, { "tatli", 1 },
            };

            foreach (StationDef st in c.Stations)
            {
                // The cuisine's own equipment is not in the docs/27 peak table;
                // that table solves the capacity of the six shared stations.
                if (!want.ContainsKey(st.Id)) continue;
                int top = 0;
                foreach (StationTier t in st.Tiers) if (t.Slots > top) top = t.Slots;
                Assert.True(want[st.Id] == top,
                    st.Id + ": the top slot count is " + top + ", docs/27 says " + want[st.Id]);
            }
        }

        [Fact]
        public void Buying_comes_out_of_the_till_and_raises_the_tier()
        {
            Simulation sim = NewSim();
            int st = UsedStation(sim);
            long before = sim.Cash;
            long price = sim.NextEquipmentPrice(st);

            Assert.True(price > 0, "the first tier appears to be free");
            Assert.Equal(0, sim.StationTier(st));

            sim.Apply(new Command(sim.TickIndex, CommandKind.BuyEquipment, st));

            Assert.Equal(1, sim.StationTier(st));
            Assert.Equal(before - price, sim.Cash);
        }

        [Fact]
        public void Someone_who_cannot_afford_it_cannot_buy_it()
        {
            Simulation sim = NewSim();
            // Find the most expensive station; the starting till must not cover it.
            int expensive = -1;
            long best = 0;
            for (int st = 0; st < sim.StationCount; st++)
            {
                long p = sim.NextEquipmentPrice(st);
                if (p > best) { best = p; expensive = st; }
            }

            // Buy the cheap ones first, to drain the till.
            for (int st = 0; st < sim.StationCount; st++)
                for (int k = 0; k < 4; k++)
                    sim.Apply(new Command(sim.TickIndex, CommandKind.BuyEquipment, st));

            _out.WriteLine($"till {sim.Cash}, most expensive {best} (station {expensive})");
            Assert.True(sim.Cash >= 0, "the till went negative buying equipment");
        }

        [Fact]
        public void A_purchase_past_the_top_tier_is_rejected()
        {
            Simulation sim = NewSim();
            ContentSet c = Content();
            int st = c.StationIndexOf("tatli");     // the shortest ladder
            Assert.True(st >= 0);

            int max = c.Stations[st].MaxTier;
            for (int i = 0; i < max; i++)
                sim.Apply(new Command(sim.TickIndex, CommandKind.BuyEquipment, st));

            Assert.Equal(max, sim.StationTier(st));
            Assert.Equal(-1, sim.NextEquipmentPrice(st));

            long cash = sim.Cash;
            sim.Apply(new Command(sim.TickIndex, CommandKind.BuyEquipment, st));
            Assert.Equal(max, sim.StationTier(st));
            Assert.Equal(cash, sim.Cash);           // no money left the till
        }

        [Fact]
        public void A_slot_upgrade_makes_a_measurable_difference()
        {
            // This is the equipment's reason to exist. If the difference cannot be
            // measured, there is nothing in return for taking the player's money.
            //
            // Two wrong set-ups were tried and both misled:
            //   1. Day one at fourteen tables: reputation 30, only 21 parties
            //      arrive, the kitchen is never stretched, the difference is zero.
            //   2. A forty-day warm-up at fourteen tables: with the maximum loan,
            //      a full crew and nine thousand in rent the restaurant goes
            //      under, the reputation falls to zero and there is no day left to
            //      measure.
            //
            // The right set-up SEPARATES THE KITCHEN FROM THE ECONOMY. Four
            // tables, one cook. At that scale the bottleneck is the slot: a party
            // of four's four main courses cook one after another on a single ring.
            // What is measured is not the number served but SATISFACTION, because
            // in a four-table place everyone gets their food in the end; what
            // varies is how long they waited.
            Simulation plain = SmallKitchen(buyEquipment: false);
            Simulation kitted = SmallKitchen(buyEquipment: true);

            // The window is twelve days, not six: once traits and named customers
            // arrived the daily swing grew and over six days the signal fell below
            // the noise (44 parties against 45, but the revenue went the OTHER
            // way). The measurement is taken over a longer window; the claim has
            // not changed.
            int servedPlain = 0, servedKitted = 0;
            long revPlain = 0, revKitted = 0;
            long satPlain = 0, satKitted = 0;
            for (int d = 0; d < 12; d++)
            {
                DayReport a = RunOneDay(plain);
                DayReport b = RunOneDay(kitted);
                servedPlain += a.ServedParties;
                servedKitted += b.ServedParties;
                revPlain += a.Revenue;
                revKitted += b.Revenue;
                satPlain += a.AverageSatisfactionCenti;
                satKitted += b.AverageSatisfactionCenti;
                _out.WriteLine(
                    $"day {d + 1}: plain {a.ServedParties}/{a.PlannedParties} " +
                    $"sat {a.AverageSatisfactionCenti / 100.0:0.0} || " +
                    $"kitted {b.ServedParties}/{b.PlannedParties} " +
                    $"sat {b.AverageSatisfactionCenti / 100.0:0.0}");
                plain.AdvanceToNextDay();
                kitted.AdvanceToNextDay();
            }

            // IS THE PLATE BOTTLENECK GETTING IN THE WAY.
            //
            // Whether a faster kitchen shows up in the revenue depends on the
            // kitchen REALLY being the bottleneck. Since the plate cycle was added
            // that is no longer a given: if the clean plates run out the cook
            // cannot send the finished dish out and both runs hit the same
            // ceiling.
            _out.WriteLine($"waited with no plate: without equipment {plain.PlateBlockedTicks} ticks, "
                           + $"with equipment {kitted.PlateBlockedTicks} ticks");
            _out.WriteLine($"total parties: without equipment {servedPlain}, with equipment {servedKitted}");
            _out.WriteLine($"total revenue: without equipment {revPlain / 100}, with equipment {revKitted / 100}");
            _out.WriteLine($"grill slots {plain.StationTier(1)} -> {kitted.StationTier(1)}");

            _out.WriteLine($"average satisfaction: without equipment {satPlain / 1200.0:0.0}, "
                           + $"with equipment {satKitted / 1200.0:0.0}");

            // THE MEASURE CHANGED BECAUSE THE MECHANISM CHANGED.
            //
            // Average satisfaction used to mislead: a narrow kitchen never served
            // the hard case at all, served the easy ones and so gave a high
            // average. That is why the measure was "the number of parties served".
            //
            // Patience now runs WHILE THE FOOD COOKS too (it used to freeze
            // because the party was marked as "in service", so the cooking time
            // cost the customer nothing at all). The customer a narrow kitchen
            // does serve now waits measurably longer and carries that in their
            // satisfaction - which means the equipment's return shows up exactly
            // where docs/27 Decision D promised it would.
            //
            // The party count is noise in a four-table place: both runs serve
            // almost everyone who comes.
            Assert.True(satKitted > satPlain,
                $"the equipment did not raise satisfaction: {satKitted} <= {satPlain}");
            // THE REVENUE IS NOISE TOO - for the same reason.
            //
            // The note above says the party count is "noise in a four-table
            // place"; so is the revenue, and it was measured: the two runs serve
            // 102 and 103 parties but the revenue is 10,225 and 10,183 - a 0.4%
            // difference whose sign depends on which party placed which order.
            // When the plate cycle was added FoodReady shifted by one tick, and
            // that WAS ENOUGH to flip the sign.
            //
            // A check that looks at the direction of a 0.4% difference is
            // measuring the seed, not the equipment. The equipment's return is in
            // SATISFACTION and there it stands at 91.2 -> 93.5 (2.3 points). What
            // is asked of the revenue is not that it rise, but that it DOES NOT
            // FALL MEANINGFULLY.
            Assert.True(revKitted * 100 >= revPlain * 95,
                $"the equipment lowered the revenue: {revKitted} < {revPlain} x0.95");
            Assert.True(servedKitted * 100 >= servedPlain * 90,
                $"the equipment lowered the service: {servedKitted} < {servedPlain} x0.9");
        }

        /// <summary>
        /// Four tables, one cook, a narrow menu. The cash is handed over directly
        /// for the equipment difference: this test measures THE KITCHEN, not the
        /// economy.
        /// </summary>
        private static Simulation SmallKitchen(bool buyEquipment)
        {
            Simulation sim = NewSim();
            sim.Apply(new Command(0, CommandKind.TakeLoan, 2));
            NarrowMenu(sim);
            if (buyEquipment)
            {
                // The cuisine's first two stations, whichever they are: fast
                // food's hob became a fryer and moved index (18 September), and
                // a test that names a station by number is a test that breaks
                // the next time the closed list grows in the middle.
                int a = UsedStation(sim, 0), b = UsedStation(sim, 1);
                for (int k = 0; k < 3; k++)
                {
                    sim.Apply(new Command(0, CommandKind.BuyEquipment, a));
                    sim.Apply(new Command(0, CommandKind.BuyEquipment, b));
                }
            }
            return sim;
        }

        // ================================================================
        // Cold storage. docs/12 3: perishable stock loses all of its value when
        // the day closes. Cold storage is the upgrade that changes THAT GROUND
        // RULE; it brings the content's spoilDays field to life.
        // ================================================================
        [Fact]
        public void The_cold_storage_ladder_loads()
        {
            ContentSet c = Content();
            Assert.NotNull(c.Storage);
            Assert.True(c.Storage.Tiers.Length >= 2);
            Assert.Equal(0, c.Storage.Tiers[0].KeepBp);     // t0: it dies overnight
            Assert.Equal(0, c.Storage.Tiers[0].Price);
            for (int t = 1; t < c.Storage.Tiers.Length; t++)
            {
                Assert.True(c.Storage.Tiers[t].KeepBp > c.Storage.Tiers[t - 1].KeepBp);
                Assert.True(c.Storage.Tiers[t].Price > c.Storage.Tiers[t - 1].Price);
            }
            Assert.Equal(10000, c.Storage.Tiers[c.Storage.MaxTier].KeepBp);
        }

        [Fact]
        public void Without_cold_storage_perishable_stock_dies_overnight()
        {
            Simulation sim = NewSim();
            ContentSet c = Content();
            Restock(sim);

            int perishable = -1, keeps = -1;
            for (int i = 0; i < c.Ingredients.Length; i++)
            {
                if (c.Ingredients[i].Perishable && perishable < 0) perishable = i;
                if (!c.Ingredients[i].Perishable && keeps < 0) keeps = i;
            }
            Assert.True(perishable >= 0 && keeps >= 0);
            Assert.True(sim.StockOf(perishable) > 0);
            Assert.True(sim.StockOf(keeps) > 0);

            sim.Apply(new Command(sim.TickIndex, CommandKind.OpenService));
            sim.Apply(new Command(sim.TickIndex, CommandKind.CloseDay));

            Assert.Equal(0, sim.StockOf(perishable));
            Assert.True(sim.StockOf(keeps) > 0, "the non-perishable stock was deleted too");
        }

        [Fact]
        public void Cold_storage_buys_shelf_life()
        {
            // At the top tier an ingredient must live for ITS OWN spoilDays.
            // Onions 20 days, mince 1 day: the two must not die the same night.
            ContentSet c = Content();
            int longLife = -1, shortLife = -1;
            for (int i = 0; i < c.Ingredients.Length; i++)
            {
                if (!c.Ingredients[i].Perishable) continue;
                if (c.Ingredients[i].SpoilDays >= 10 && longLife < 0) longLife = i;
                if (c.Ingredients[i].SpoilDays == 1 && shortLife < 0) shortLife = i;
            }
            Assert.True(longLife >= 0, "there is no perishable ingredient that lives longer than ten days");
            Assert.True(shortLife >= 0, "there is no one-day perishable ingredient");

            Simulation sim = NewSim();
            sim.Apply(new Command(0, CommandKind.TakeLoan, 2));
            for (int k = 0; k < c.Storage.MaxTier; k++)
                sim.Apply(new Command(0, CommandKind.BuyStorage));
            Assert.Equal(c.Storage.MaxTier, sim.StorageTier);

            Restock(sim);
            int had = sim.StockOf(longLife);
            Assert.True(had > 0);

            // Close a day with no service: let only the spoilage run.
            sim.Apply(new Command(sim.TickIndex, CommandKind.OpenService));
            sim.Apply(new Command(sim.TickIndex, CommandKind.CloseDay));

            _out.WriteLine($"{c.Ingredients[longLife].Id} ({c.Ingredients[longLife].SpoilDays} days): " +
                           $"{had} -> {sim.StockOf(longLife)}");
            _out.WriteLine($"{c.Ingredients[shortLife].Id} ({c.Ingredients[shortLife].SpoilDays} days): " +
                           $"{sim.StockOf(shortLife)}");

            Assert.True(sim.StockOf(longLife) > 0, "the long-lived ingredient died even in cold storage");
            Assert.Equal(0, sim.StockOf(shortLife));
        }

        [Fact]
        public void Buying_one_gram_to_stop_the_clock_does_not_work()
        {
            // The age is a WEIGHTED AVERAGE. A simple "reset on purchase" rule
            // opened this exploit up: by buying one gram a day you could keep an
            // ingredient fresh for ever.
            ContentSet c = Content();
            int ing = -1;
            for (int i = 0; i < c.Ingredients.Length; i++)
                if (c.Ingredients[i].Perishable && c.Ingredients[i].SpoilDays >= 3
                    && c.Ingredients[i].SpoilDays <= 6) { ing = i; break; }
            Assert.True(ing >= 0);

            Simulation sim = NewSim();
            sim.Apply(new Command(0, CommandKind.TakeLoan, 2));
            for (int k = 0; k < c.Storage.MaxTier; k++)
                sim.Apply(new Command(0, CommandKind.BuyStorage));

            sim.Apply(new Command(sim.TickIndex, CommandKind.OrderIngredient, ing, 40_000));

            int survived = 0;
            for (int d = 0; d < 12; d++)
            {
                sim.Apply(new Command(sim.TickIndex, CommandKind.OrderIngredient, ing, 1));
                sim.Apply(new Command(sim.TickIndex, CommandKind.OpenService));
                sim.Apply(new Command(sim.TickIndex, CommandKind.CloseDay));
                // The threshold IS NOT ZERO. The daily one-gram purchase keeps
                // the stock technically above zero and it looks "alive"; what has
                // to be measured is whether THE FIRST BATCH survives.
                if (sim.StockOf(ing) > 1_000) survived++;
                sim.AdvanceToNextDay();
            }

            _out.WriteLine($"{c.Ingredients[ing].Id} ({c.Ingredients[ing].SpoilDays} days of shelf life): " +
                           $"survived {survived} days by buying one gram a day");
            Assert.True(survived <= c.Ingredients[ing].SpoilDays,
                $"the shelf life was beaten by buying one gram: {survived} > {c.Ingredients[ing].SpoilDays}");
        }

        [Fact]
        public void The_save_carries_the_equipment_tier_and_the_work_in_progress()
        {
            Simulation sim = NewSim();
            int a = UsedStation(sim, 0), b = UsedStation(sim, 1);
            sim.Apply(new Command(sim.TickIndex, CommandKind.BuyEquipment, a));
            sim.Apply(new Command(sim.TickIndex, CommandKind.BuyEquipment, b));

            // Save in the middle of service: there is work cooking at a station.
            sim.Apply(new Command(sim.TickIndex, CommandKind.OpenService));
            for (int t = 0; t < 1200; t++) sim.Tick();

            JsonStateWriter w = new JsonStateWriter();
            sim.Write(w);
            Simulation restored = NewSim();
            restored.Restore(new JsonStateReader(w.ToJson()));

            // The tiers must be NON-ZERO, or this compares nothing: the buys
            // above are refused for a station the cuisine does not use, and
            // 0 == 0 passes without testing the save at all.
            Assert.True(sim.StationTier(a) > 0, "the first buy did not take");
            Assert.Equal(sim.StationTier(a), restored.StationTier(a));
            Assert.Equal(sim.StationTier(b), restored.StationTier(b));
            Assert.Equal(sim.StateHash(), restored.StateHash());

            // It must end the same as an uninterrupted run: the slot counter is
            // DERIVED, so it is rebuilt; if it is rebuilt wrongly the kitchen
            // silently narrows and the difference is only visible here.
            for (int t = 0; t < 3600; t++) { sim.Tick(); restored.Tick(); }
            Assert.Equal(sim.StateHash(), restored.StateHash());
        }
    }
}
